### ISSUE TITLE
speedtest-cli broken on debian - replace it with ookla speedtest

### ISSUE THREAD

**Issue by nikobo** [Varik001/zabbix-appliance-speedtest-wan#3]
Hello,

On  debian 10.9
```
cat /etc/debian_version
10.9
```
speedtest-cli package is broken : 
```
# speedtest
Retrieving speedtest.net configuration...
Traceback (most recent call last):
  File "/usr/bin/speedtest", line 11, in <module>
    load_entry_point('speedtest-cli==2.0.2', 'console_scripts', 'speedtest')()
  File "/usr/lib/python3/dist-packages/speedtest.py", line 1887, in main
    shell()
  File "/usr/lib/python3/dist-packages/speedtest.py", line 1783, in shell
    secure=args.secure
  File "/usr/lib/python3/dist-packages/speedtest.py", line 1027, in __init__
    self.get_config()
  File "/usr/lib/python3/dist-packages/speedtest.py", line 1113, in get_config
    map(int, server_config['ignoreids'].split(','))
ValueError: invalid literal for int() with base 10: ''
```
https://unix.stackexchange.com/questions/644442/speedtest-cli-valueerror-invalid-literal-for-int-with-base-10

Maybe, it should be replaced with the ookla package ?
https://www.speedtest.net/apps/cli

**Comment by nikobo** [comment]
```
        #Check if argument supplied to function, exec speedtest command and save output
        if [ -z "$1" ]
        then
                output=$(speedtest -f json-pretty)
        else
                output=$(speedtest -f json-pretty --server-id="$1")
                CACHE_FILE+="_$1"
        fi
```

```
        case "$1" in
                -c|--cached)
                        check_cache_exist "$CACHE_FILE"
                        cat "$CACHE_FILE"
                        ;;
                -u|--upload)
                        check_cache_exist "$CACHE_FILE"
                        cat "$CACHE_FILE" | python -c "import sys, json; print json.load(sys.stdin)['upload']['bandwidth']"
                        ;;
                -d|--download)
                        check_cache_exist "$CACHE_FILE"
                        cat "$CACHE_FILE" | python -c "import sys, json; print json.load(sys.stdin)['download']['bandwidth']"
                        ;;
                -p|--ping)
                        check_cache_exist "$CACHE_FILE"
                        cat "$CACHE_FILE" | python -c "import sys, json; print json.load(sys.stdin)['ping']['latency']"
                        ;;
                -f|--force)
                        rm -rf "$LOCK_FILE"
                        run_speedtest
                        ;;
                -h|--help)
                        display_help
                        ;;
                *)
                        run_speedtest
                        ;;
```

**Comment by valerio-bozzolan** [comment]
I confirm that in Debian 10 and in Ubuntu 20.04 LTS the `speedtest-cli` is broken (version `2.0.2-1+deb10u1`).

Upstream bug:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=986637

**Comment by valerio-bozzolan** [comment]
Hi @nikobo. I created a patch ([speedtest-cli-patch.txt](https://github.com/Varik001/zabbix-appliance-speedtest-wan/files/6575394/speedtest-cli-patch.txt)) to fix Debian 10 and Ubuntu 20.04 LTS and maybe other GNU/Linux distributions.

To apply my patch:

```
wget https://github.com/Varik001/zabbix-appliance-speedtest-wan/files/6575394/speedtest-cli-patch.txt
sudo patch /usr/lib/python3/dist-packages/speedtest.py speedtest-cli-patch.txt
```

 :heavy_check_mark:  Fixed.

My patch just applies this changeset:

https://github.com/sivel/speedtest-cli/commit/cadc68b5aef20f28648072cf07a8f155639b81dd#diff-561d5175f923c2ffd7764768f8e3cd6e1fdb41806bf1b0e4da699ab21bb31930

I don't know if it is appropriate to change the backend of this package in the meantime just for this upstream bug.
